[package]
name = "hexie"
version = "0.1.0"
authors = ["Sam <samwho@lbak.co.uk>"]
edition = "2018"

[dependencies]
term_size = "0.3.1"
clap = "2.33.0"
colored = "1.7"
hex = "0.3.2"
log = "0.4.6"
env_logger = "0.6.1"